### PR TITLE
Upgraded dependencies, dropped PHP < 7.3

### LINKED ISSUE #64: `php:~8.0.0` support
Not much to be said here, other than needing to widen ranges and try out stuff again before releasing :-)

### PR DESCRIPTION
**Pull request by Ocramius**
Fixes #64

### CODE REVIEW

**Comment by Ocramius** [comment]
Overall would endorse bumping dependency ranges. Also, travis-ci will probably hang forever here.

**Comment by WyriHaximus** [comment]
> Overall would endorse bumping dependency ranges.

Going to update this, and several other external packages I maintain to include Dependabot and GitHub Actions this week.

> Also, travis-ci will probably hang forever here.

Travis now fails because `composer.lock` seems out of date.

**Comment by Ocramius** [comment]
Besides this CI hiccup, seems alright:

```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/14.04/x86_64/php-8.0.tar.bz2

0.04s$ curl -sSf --retry 5 -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /

curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by Ocramius** [comment]
Hmmmm no, seems like we need to upgrade the base image overall.

**Comment by Ocramius** [comment]
ah yes, need to update patch to run CS tools on PHP 8.x :-)

**Comment by WyriHaximus** [comment]
@Ocramius FYI I started working to update to GA in #66, once this PR is in I'll enable Dependabot. Might have to ping @jwage for both

**Comment by WyriHaximus** [comment]
@Ocramius #66 has been merged, could you rebase this PR?

**Comment by Ocramius** [comment]
@WyriHaximus I think `ocular` is not PHP 8-ready. Can I kill it, so we kill scrutinizer overall?

**Comment by WyriHaximus** [comment]
> @WyriHaximus I think `ocular` is not PHP 8-ready. Can I kill it, so we kill scrutinizer overall?

@jwage Assuming we'd still want to coverage percentage badge in the readme? Personally, I've started replacing scrutinized with coveralls.io, suppose we can do a follow up adding coveralls or something else soon after nuking scrutinized?

**Comment by Ocramius** [comment]
I'm personally dropping all of these third-party tools, replacing them with `infection/infection`.

I'll kill scrutinizer, for now :-)

**Comment by Ocramius** [comment]
@WyriHaximus I managed to keep Scrutinizer-CI, but making it a bit more lax on failures on `ocular.phar`

**Comment by Ocramius** [comment]
> The base branch requires all commits to be signed.

OOOOOOOF.

**Comment by WyriHaximus** [comment]
> > The base branch requires all commits to be signed.
> 
> OOOOOOOF.

Do you have that set up somewhere, or do you want me or @jwage to do something about that?

**Comment by Ocramius** [comment]
It's a branch protection rule, but I just rebased with `git rebase --exec 'git commit --amend --no-edit -n -S' -i master` and entered my GPG password a few times :P

**Pull request merged**
